# Generated by Django 3.2 on 2021-07-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0006_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(default=9999999999),
        ),
    ]
