# Generated by Django 3.2 on 2021-07-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0007_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
