# Generated by Django 3.2 on 2021-07-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starrate',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
