# Generated by Django 3.2 on 2021-07-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0010_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
