# Generated by Django 3.2 on 2021-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0011_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='starrate',
            field=models.IntegerField(null=True),
        ),
    ]
