# Generated by Django 3.2 on 2021-07-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyProject', '0013_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
    ]
